%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: E:\Research_Projects\MiddleAge_LARA\STATS\1_PreliminaryAnalysis\data_wrangling\AGE_COG_data_155Subj.csv
%
% Auto-generated by MATLAB on 18-Jan-2024 10:58:58

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Subj_ID", "Observations", "Age_Cog", "age", "hand", "gender_code", "MMSE", "Cattell", "Proverb", "Naming", "ToT_Ratio", "Hotel_Task", "Sentence_Comprehension_c", "Story_Recall", "Verbal_Fluency"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Observations", "TrimNonNumeric", true);
opts = setvaropts(opts, "Observations", "ThousandsSeparator", ",");

% Import the data
AGECOGdata155Subj = readtable("E:\Research_Projects\MiddleAge_LARA\STATS\1_PreliminaryAnalysis\data_wrangling\AGE_COG_data_155Subj.csv", opts);

%% Convert to output type
AGECOGdata155Subj = table2array(AGECOGdata155Subj);

%% Clear temporary variables
clear opts