%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\Research_Projects\MiddleAge_LARA\DWI\participant_data_DTI.xlsx
%    Worksheet: Feuil2
%
% Auto-generated by MATLAB on 18-Jan-2024 11:12:02

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "TIV";
opts.DataRange = "A1:A155";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Import the data
participantdataDTIS1 = readtable("E:\Research_Projects\MiddleAge_LARA\DWI\participant_data_DTI.xlsx", opts, "UseExcel", false);

%% Convert to output type
participantdataDTIS1 = table2array(participantdataDTIS1);

%% Clear temporary variables
clear opts